/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nithi
 */
public class language extends javax.swing.JFrame {

    /**
     * Creates new form language
     */
    public language() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        hover = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Constantia", 2, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("XTREME MOVIES");
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 150, -1));

        jPanel2.setBackground(new java.awt.Color(30, 28, 32));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_home_page_25px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 0, -1, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("HOME");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 10, 120, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 230, 10));

        jPanel3.setBackground(new java.awt.Color(30, 28, 32));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(280, 53));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_login_30px.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 0, 39, 40));

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LOGIN");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 10, 100, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 280, 50));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(280, 53));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_cinema_25px_2.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 11, 39, 28));

        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("MOVIES");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 11, 103, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 280, 50));

        jPanel5.setBackground(new java.awt.Color(30, 28, 32));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(280, 53));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_card_payment_25px.png"))); // NOI18N

        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("PAYMENTS");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 280, 50));

        jPanel6.setBackground(new java.awt.Color(30, 28, 32));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_coming_soon_25px.png"))); // NOI18N

        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("COMING SOON");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 280, 50));

        jPanel7.setBackground(new java.awt.Color(30, 28, 32));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_system_report_25px.png"))); // NOI18N

        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("REVIEWS");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addGap(0, 16, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 280, 50));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 20, 730));

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("1/3");
        jTextField2.setBorder(null);
        jPanel8.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 670, 30, 30));

        jPanel9.setPreferredSize(new java.awt.Dimension(200, 300));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\nithi\\Desktop\\project\\pics\\the-imitation-game-movie-poster-200x300.jpg")); // NOI18N
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel7MouseMoved(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 200, 300));

        jPanel11.setPreferredSize(new java.awt.Dimension(200, 300));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\nithi\\Desktop\\project\\pics\\s-l300 (1).jpg")); // NOI18N
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel8MouseMoved(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 90, 200, 300));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\nithi\\Desktop\\project\\pics\\aladdin-2019-movie-poster-6197.jpg")); // NOI18N
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel9MouseMoved(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 200, 300));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\nithi\\Desktop\\project\\pics\\cb62d849787560e32013e40a0f8faa63.jpg")); // NOI18N
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 200, 300));

        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_back_to_30px.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 670, 30, 30));

        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_next_page_30px_1.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 20, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 20, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 20, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 20, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_half_15px.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 20, 20));

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("2019 -   ACTION/COMEDY   -  2H2M");
        jTextField3.setBorder(null);
        jPanel8.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 200, 20));

        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("ENGLISH - SCREEN 1");
        jTextField4.setBorder(null);
        jPanel8.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 210, 40));

        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("8.5/10 --  IMDB");
        jTextField5.setBorder(null);
        jPanel8.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 90, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 20, 20));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 20, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel20.setText("jLabel20");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 20, 20));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 20, 20));

        jTextField7.setBackground(new java.awt.Color(0, 0, 0));
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("2019-  FAMIL/ROMANCE -  2H8M");
        jTextField7.setBorder(null);
        jPanel8.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 200, 20));

        jTextField8.setBackground(new java.awt.Color(0, 0, 0));
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setText("7/10--IMDB");
        jTextField8.setBorder(null);
        jPanel8.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 70, -1));

        jTextField9.setBackground(new java.awt.Color(0, 0, 0));
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("2014 -   WAR/DRAMA   -  1H54M");
        jTextField9.setBorder(null);
        jPanel8.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 190, 20));

        jTextField10.setBackground(new java.awt.Color(0, 0, 0));
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setText("8/10 --IMDB");
        jTextField10.setBorder(null);
        jPanel8.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 90, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel22.setText("jLabel22");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 20, 20));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel23.setText("jLabel23");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 20, 20));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel24.setText("jLabel24");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 20, 20));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel25.setText("jLabel25");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 20, 20));

        jTextField11.setBackground(new java.awt.Color(0, 0, 0));
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setText("2019- ACTION/THRILLER- 2H23M");
        jTextField11.setBorder(null);
        jPanel8.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, 200, 20));

        jTextField12.setBackground(new java.awt.Color(0, 0, 0));
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setText("7.4/10--IMDB");
        jTextField12.setBorder(null);
        jPanel8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 80, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel26.setText("jLabel26");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 410, 20, 20));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel27.setText("jLabel27");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, 20, 20));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel28.setText("jLabel28");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 20, 20));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel29.setText("jLabel29");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, 20, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_cinema_25px_2.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 40, 30));

        hover.setBackground(new java.awt.Color(0, 0, 0));
        hover.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        hover.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 180, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 51));
        jLabel19.setText("BOOK NOW");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 100, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 51));
        jLabel30.setText("BOOK NOW");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 110, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 51));
        jLabel31.setText("BOOK NOW");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 110, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 51));
        jLabel32.setText("BOOK NOW");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 110, 30));

        jTextField6.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("TIME");
        jTextField6.setBorder(null);
        jPanel8.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 544, 50, 30));

        jTextField13.setBackground(new java.awt.Color(0, 0, 0));
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setText("DATE");
        jTextField13.setBorder(null);
        jPanel8.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 50, 30));

        jTextField14.setBackground(new java.awt.Color(0, 0, 0));
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setBorder(null);
        jPanel8.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 100, 30));

        jTextField15.setBackground(new java.awt.Color(0, 0, 0));
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setBorder(null);
        jPanel8.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 90, 30));

        jTextField16.setBackground(new java.awt.Color(0, 0, 0));
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jTextField16.setText("TIME");
        jTextField16.setBorder(null);
        jPanel8.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 30, 30));

        jTextField17.setBackground(new java.awt.Color(0, 0, 0));
        jTextField17.setForeground(new java.awt.Color(255, 255, 255));
        jTextField17.setText("DATE");
        jTextField17.setBorder(null);
        jPanel8.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 50, 30));

        jTextField18.setBackground(new java.awt.Color(0, 0, 0));
        jTextField18.setForeground(new java.awt.Color(255, 255, 255));
        jTextField18.setBorder(null);
        jPanel8.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 100, 30));

        jTextField19.setBackground(new java.awt.Color(0, 0, 0));
        jTextField19.setForeground(new java.awt.Color(255, 255, 255));
        jTextField19.setBorder(null);
        jPanel8.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 100, 30));

        jTextField20.setBackground(new java.awt.Color(0, 0, 0));
        jTextField20.setForeground(new java.awt.Color(255, 255, 255));
        jTextField20.setText("TIME");
        jTextField20.setBorder(null);
        jPanel8.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 60, 30));

        jTextField21.setBackground(new java.awt.Color(0, 0, 0));
        jTextField21.setForeground(new java.awt.Color(255, 255, 255));
        jTextField21.setText("DATE");
        jTextField21.setBorder(null);
        jPanel8.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 60, 30));

        jTextField22.setBackground(new java.awt.Color(0, 0, 0));
        jTextField22.setForeground(new java.awt.Color(255, 255, 255));
        jTextField22.setBorder(null);
        jPanel8.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 90, 30));

        jTextField23.setBackground(new java.awt.Color(0, 0, 0));
        jTextField23.setForeground(new java.awt.Color(255, 255, 255));
        jTextField23.setBorder(null);
        jPanel8.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, 90, 30));

        jTextField24.setBackground(new java.awt.Color(0, 0, 0));
        jTextField24.setForeground(new java.awt.Color(255, 255, 255));
        jTextField24.setText("TIME");
        jTextField24.setBorder(null);
        jPanel8.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, 50, 30));

        jTextField25.setBackground(new java.awt.Color(0, 0, 0));
        jTextField25.setForeground(new java.awt.Color(255, 255, 255));
        jTextField25.setText("DATE");
        jTextField25.setBorder(null);
        jPanel8.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, 50, 30));

        jTextField26.setBackground(new java.awt.Color(0, 0, 0));
        jTextField26.setForeground(new java.awt.Color(255, 255, 255));
        jTextField26.setBorder(null);
        jPanel8.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, 80, 30));

        jTextField27.setBackground(new java.awt.Color(0, 0, 0));
        jTextField27.setForeground(new java.awt.Color(255, 255, 255));
        jTextField27.setBorder(null);
        jPanel8.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, 80, 30));

        jTextField28.setBackground(new java.awt.Color(0, 0, 0));
        jTextField28.setForeground(new java.awt.Color(255, 255, 255));
        jTextField28.setText("SCREEN");
        jTextField28.setBorder(null);
        jPanel8.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 80, -1));

        jTextField29.setBackground(new java.awt.Color(0, 0, 0));
        jTextField29.setForeground(new java.awt.Color(255, 255, 255));
        jTextField29.setBorder(null);
        jPanel8.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, 70, -1));

        jTextField30.setBackground(new java.awt.Color(0, 0, 0));
        jTextField30.setForeground(new java.awt.Color(255, 255, 255));
        jTextField30.setText(" SCREEN");
        jTextField30.setBorder(null);
        jPanel8.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 70, -1));

        jTextField31.setBackground(new java.awt.Color(0, 0, 0));
        jTextField31.setForeground(new java.awt.Color(255, 255, 255));
        jTextField31.setBorder(null);
        jPanel8.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 80, 30));

        jTextField32.setBackground(new java.awt.Color(0, 0, 0));
        jTextField32.setForeground(new java.awt.Color(255, 255, 255));
        jTextField32.setText("SCREEN");
        jTextField32.setBorder(null);
        jPanel8.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 70, -1));

        jTextField33.setBackground(new java.awt.Color(0, 0, 0));
        jTextField33.setForeground(new java.awt.Color(255, 255, 255));
        jTextField33.setBorder(null);
        jPanel8.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 620, 70, -1));

        jTextField34.setBackground(new java.awt.Color(0, 0, 0));
        jTextField34.setForeground(new java.awt.Color(255, 255, 255));
        jTextField34.setText(" SCREEN");
        jTextField34.setBorder(null);
        jPanel8.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, 60, -1));

        jTextField35.setBackground(new java.awt.Color(0, 0, 0));
        jTextField35.setForeground(new java.awt.Color(255, 255, 255));
        jTextField35.setBorder(null);
        jPanel8.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 620, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
new login().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);
new loginpage().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
this.setVisible(false);
new movies2().setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
this.setVisible(false);
new register().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
hover.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseMoved
hover.setText("THE IMITATION GAME");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseMoved

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
hover.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseMoved
hover.setText("JOKER");
     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseMoved

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
hover.setText("");

       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseMoved
hover.setText("ALADDIN");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseMoved

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved
hover.setText("JOHN WICK 3");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseMoved

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
hover.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(language.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(language.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(language.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(language.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new language().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hover;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
