/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nithi
 */
public class movies2 extends javax.swing.JFrame {

    /**
     * Creates new form movies2
     */
    public movies2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        hover = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Constantia", 2, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("XTREME MOVIES");
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 140, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 62, 220, 10));

        jPanel3.setBackground(new java.awt.Color(30, 28, 32));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_login_30px.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, -1, 40, 40));

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LOGIN");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 100, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 280, 50));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_cinema_25px_2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 30));

        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("MOVIES");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 80, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 280, 50));

        jPanel5.setBackground(new java.awt.Color(30, 28, 32));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_card_payment_25px.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 11, 42, 28));

        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("PAYMENTS");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 90, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 280, 50));

        jPanel6.setBackground(new java.awt.Color(30, 28, 32));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_coming_soon_25px.png"))); // NOI18N
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 30));

        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("COMING SOON");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 280, 50));

        jPanel7.setBackground(new java.awt.Color(30, 28, 32));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_system_report_25px.png"))); // NOI18N
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 30, 28));

        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("REVIEWS");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jPanel7.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 70, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 280, 50));

        jPanel13.setBackground(new java.awt.Color(30, 28, 32));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_home_page_25px.png"))); // NOI18N
        jPanel13.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 30));

        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("HOME");
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jPanel13.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 80, 30));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 50));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 20, 720));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_back_to_30px.png"))); // NOI18N
        jButton7.setText("jButton7");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 660, 40, -1));

        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_next_page_30px_1.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 660, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("2/3");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 660, 20, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\nithi\\Desktop\\project\\pics\\New folder\\ad1d772d04f2a1d04b70a4879240501c.jpg")); // NOI18N
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel8MouseMoved(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 200, 300));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\nithi\\Desktop\\project\\pics\\DIA.jpg")); // NOI18N
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel9MouseMoved(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 200, 300));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\nithi\\Desktop\\project\\pics\\New folder\\Yajamana-Kannada-Movie-Poster-Cinema-200x300.jpg")); // NOI18N
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 200, 300));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\nithi\\Desktop\\project\\pics\\New folder\\727d610e9001865f71140357c57cc829.jpg")); // NOI18N
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel11MouseMoved(evt);
            }
        });
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 200, 300));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 20, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 20, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 20, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 20, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_half_15px.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 20, 20));

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("2018 -  ACTION/DRAMA -  2H54M");
        jTextField2.setBorder(null);
        jPanel8.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 200, -1));

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("8.2/10-IMDB");
        jTextField3.setBorder(null);
        jPanel8.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 80, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 20, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 20, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel19.setText("jLabel19");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 20, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_half_15px.png"))); // NOI18N
        jLabel20.setText("jLabel20");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 20, 30));

        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("2019 - ACTION/DRAMA - 2H44M");
        jTextField4.setBorder(null);
        jPanel8.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 200, -1));

        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("6.7/10-IMDB");
        jTextField5.setBorder(null);
        jPanel8.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 80, 20));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 20, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel22.setText("jLabel22");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 20, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel23.setText("jLabel23");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 20, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel24.setText("jLabel24");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 20, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_half_15px.png"))); // NOI18N
        jLabel25.setText("jLabel25");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 30, -1));

        jTextField6.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("2020 - DRAMA/ROMANCE - 2H16M");
        jTextField6.setBorder(null);
        jPanel8.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 200, 30));

        jTextField7.setBackground(new java.awt.Color(0, 0, 0));
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("8.2/10-IMDB");
        jTextField7.setBorder(null);
        jPanel8.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 80, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel26.setText("jLabel26");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 20, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel27.setText("jLabel27");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 20, 30));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_15px_1.png"))); // NOI18N
        jLabel28.setText("jLabel28");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 400, 20, 30));

        jTextField8.setBackground(new java.awt.Color(0, 0, 0));
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setText("2018 - ACTION/THRILLER - 2H55M");
        jTextField8.setBorder(null);
        jPanel8.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 200, 30));

        jTextField9.setBackground(new java.awt.Color(0, 0, 0));
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("5.5/10-IMDB");
        jTextField9.setBorder(null);
        jPanel8.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, -1, -1));

        jTextField10.setBackground(new java.awt.Color(0, 0, 0));
        jTextField10.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setText("KANNADA");
        jTextField10.setBorder(null);
        jPanel8.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 220, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_cinema_25px_2.png"))); // NOI18N
        jLabel29.setText("jLabel29");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, 30, 30));

        hover.setBackground(new java.awt.Color(255, 255, 255));
        hover.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        hover.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 660, 180, 30));

        jPanel2.setBackground(new java.awt.Color(30, 28, 32));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_home_page_25px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 30, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("HOME");
        jButton1.setToolTipText("");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 11, 90, 30));

        jPanel8.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 120, 280, 50));

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 51));
        jLabel30.setText("BOOK NOW");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 120, 40));

        jLabel31.setBackground(new java.awt.Color(0, 0, 0));
        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 51));
        jLabel31.setText("BOOK NOW");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 110, 30));

        jLabel33.setBackground(new java.awt.Color(0, 0, 0));
        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 0, 51));
        jLabel33.setText("BOOK NOW");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 120, 30));

        jLabel34.setBackground(new java.awt.Color(0, 0, 0));
        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 0, 51));
        jLabel34.setText("BOOK NOW");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, 100, 30));

        jTextField11.setBackground(new java.awt.Color(0, 0, 0));
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setText("TIME");
        jTextField11.setBorder(null);
        jPanel8.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 50, -1));

        jTextField12.setBackground(new java.awt.Color(0, 0, 0));
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setText("DATE");
        jTextField12.setBorder(null);
        jPanel8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 564, 50, 30));

        jTextField13.setBackground(new java.awt.Color(0, 0, 0));
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setBorder(null);
        jPanel8.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 70, 20));

        jTextField14.setBackground(new java.awt.Color(0, 0, 0));
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setBorder(null);
        jPanel8.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 70, 30));

        jTextField15.setBackground(new java.awt.Color(0, 0, 0));
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setText("TIME");
        jTextField15.setBorder(null);
        jPanel8.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 40, 20));

        jTextField16.setBackground(new java.awt.Color(0, 0, 0));
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jTextField16.setText("DATE");
        jTextField16.setBorder(null);
        jPanel8.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 40, 20));

        jTextField17.setBackground(new java.awt.Color(0, 0, 0));
        jTextField17.setForeground(new java.awt.Color(255, 255, 255));
        jTextField17.setBorder(null);
        jPanel8.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 60, -1));

        jTextField18.setBackground(new java.awt.Color(0, 0, 0));
        jTextField18.setForeground(new java.awt.Color(255, 255, 255));
        jTextField18.setBorder(null);
        jPanel8.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 70, -1));

        jTextField19.setBackground(new java.awt.Color(0, 0, 0));
        jTextField19.setForeground(new java.awt.Color(255, 255, 255));
        jTextField19.setText("TIME");
        jTextField19.setBorder(null);
        jPanel8.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, -1, -1));

        jTextField20.setBackground(new java.awt.Color(0, 0, 0));
        jTextField20.setForeground(new java.awt.Color(255, 255, 255));
        jTextField20.setText("DATE");
        jTextField20.setBorder(null);
        jPanel8.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 40, 20));

        jTextField21.setBackground(new java.awt.Color(0, 0, 0));
        jTextField21.setForeground(new java.awt.Color(255, 255, 255));
        jTextField21.setBorder(null);
        jPanel8.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 70, 20));

        jTextField22.setBackground(new java.awt.Color(0, 0, 0));
        jTextField22.setForeground(new java.awt.Color(255, 255, 255));
        jTextField22.setBorder(null);
        jPanel8.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 70, 20));

        jTextField23.setBackground(new java.awt.Color(0, 0, 0));
        jTextField23.setForeground(new java.awt.Color(255, 255, 255));
        jTextField23.setText("TIME");
        jTextField23.setBorder(null);
        jPanel8.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, 50, 20));

        jTextField24.setBackground(new java.awt.Color(0, 0, 0));
        jTextField24.setForeground(new java.awt.Color(255, 255, 255));
        jTextField24.setText("DATE");
        jTextField24.setBorder(null);
        jPanel8.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 40, 20));

        jTextField25.setBackground(new java.awt.Color(0, 0, 0));
        jTextField25.setForeground(new java.awt.Color(255, 255, 255));
        jTextField25.setBorder(null);
        jPanel8.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 530, 80, 30));

        jTextField26.setBackground(new java.awt.Color(0, 0, 0));
        jTextField26.setForeground(new java.awt.Color(255, 255, 255));
        jTextField26.setBorder(null);
        jPanel8.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 560, 90, 30));

        jTextField27.setBackground(new java.awt.Color(0, 0, 0));
        jTextField27.setForeground(new java.awt.Color(255, 255, 255));
        jTextField27.setText("SCREEN");
        jTextField27.setBorder(null);
        jPanel8.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 60, 30));

        jTextField28.setBackground(new java.awt.Color(0, 0, 0));
        jTextField28.setForeground(new java.awt.Color(255, 255, 255));
        jTextField28.setBorder(null);
        jPanel8.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 70, 30));

        jTextField29.setBackground(new java.awt.Color(0, 0, 0));
        jTextField29.setForeground(new java.awt.Color(255, 255, 255));
        jTextField29.setText("SCREEN");
        jTextField29.setBorder(null);
        jPanel8.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, 70, 30));

        jTextField30.setBackground(new java.awt.Color(0, 0, 0));
        jTextField30.setForeground(new java.awt.Color(255, 255, 255));
        jTextField30.setBorder(null);
        jPanel8.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 80, 30));

        jTextField31.setBackground(new java.awt.Color(0, 0, 0));
        jTextField31.setForeground(new java.awt.Color(255, 255, 255));
        jTextField31.setText("SCREEN");
        jTextField31.setBorder(null);
        jPanel8.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 600, 70, 30));

        jTextField32.setBackground(new java.awt.Color(0, 0, 0));
        jTextField32.setForeground(new java.awt.Color(255, 255, 255));
        jTextField32.setBorder(null);
        jPanel8.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 600, 80, 30));

        jTextField33.setBackground(new java.awt.Color(0, 0, 0));
        jTextField33.setForeground(new java.awt.Color(255, 255, 255));
        jTextField33.setText("SCREEN");
        jTextField33.setBorder(null);
        jPanel8.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 70, 30));

        jTextField34.setBackground(new java.awt.Color(0, 0, 0));
        jTextField34.setForeground(new java.awt.Color(255, 255, 255));
        jTextField34.setBorder(null);
        jPanel8.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
this.setVisible(false);
new movies3().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
this.setVisible(false);
new language().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
new login().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);
new loginpage().setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
hover.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseMoved
 hover.setText("K.G.F");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseMoved

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
hover.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseMoved
hover.setText("DIA");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseMoved

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
hover.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved
hover.setText("YAJAMANA");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseMoved

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
hover.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseMoved
hover.setText("VILLAIN");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseMoved

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
this.setVisible(false);
new comingsoon().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.setVisible(false);
new payments().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movies2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movies2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movies2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movies2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movies2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hover;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
